BEGIN;
DO $$
    BEGIN
        IF NOT EXISTS(select 1 from pg_roles where rolname = 'DBAUSER') THEN
            CREATE USER DBAUSER WITH PASSWORD 'DBAPASS';
            GRANT ALL PRIVILEGES ON DATABASE "DBNAME" TO DBAUSER;            
            ALTER ROLE DBAUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
        END IF;
        GRANT ALL PRIVILEGES ON SCHEMA public TO DBAUSER;
        IF NOT EXISTS(select 1 from pg_roles where rolname='APPUSER') THEN
            CREATE USER APPUSER WITH PASSWORD 'APPPASS';
            ALTER ROLE APPUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
        END IF;
        GRANT USAGE ON SCHEMA public TO APPUSER;
    END
$$;
