REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM orm_dba;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM orm_dba;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM orm_dba;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM orm_dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM orm_dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM orm_dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM orm_dba;
REVOKE USAGE ON SCHEMA public FROM orm_dba;
DROP USER orm_dba;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM orm_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM orm_app;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM orm_app;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM orm_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM orm_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM orm_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM orm_app;
REVOKE USAGE ON SCHEMA public FROM orm_app;
DROP USER orm_app;