apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-volume
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/log"
