apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-st-webapi.fullname" . }}
  labels:
    {{- include "poc-st-webapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "poc-st-webapi.selectorLabels" . | nindent 4 }}
