version: "3.1"
services:
  poc-st-jaeger:
    image: jaegertracing/all-in-one:1.70.0
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  poc-st-prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  poc-st-grafana:
    container_name: grafana
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
  poc-st-otel-collector:
    image: otel/opentelemetry-collector-contrib:0.129.1
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"
      - "55679:55679" # zpages extension
    depends_on:
      - poc-st-jaeger
      - poc-st-prometheus
