global:
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  scrape_interval: 5s   

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['poc-st-otel-collector:8889']
      - targets: ['poc-st-otel-collector:8888']
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: poc-spring-telemetry
    scrape_interval: 5s
    metrics_path: '/poc-st/actuator/prometheus'
    static_configs:
      - targets: ["192.168.1.15:8080"]
    basic_auth:
      username: admin
      password: admin
  #- job_name: node
  #  static_configs:
  #    - targets: ["node-exporter:8889"]