FROM eclipse-temurin:23.0.2_7-jdk-alpine-3.21 AS customjre
ARG JAR_FILE

WORKDIR /app
RUN apk add --no-cache unzip
COPY ${JAR_FILE} app.jar
RUN jlink --compress=2 --no-header-files --no-man-pages --add-modules java.base,java.desktop,java.instrument,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.sql.rowset,jdk.compiler,jdk.jfr,jdk.management,jdk.unsupported,org.graalvm.nativeimage  --output /app/customjre

FROM alpine:3.19.1
EXPOSE 8080/tcp
RUN addgroup -g 101 -S appgrp && \
    adduser -u 100 -S appusr -G appgrp && \
    mkdir -p /app/ && \
    chown appusr /app/ && \
    apk add --no-cache curl jq
USER appusr
COPY --from=customjre /app/customjre /app/customjre
COPY --from=customjre /app/app.jar /app/app.jar
ENV JAVA_HOME=/app/customjre
CMD ["/app/customjre/bin/java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]