# code: language=ansible
---
- name: OpenBao Configuration
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Get ipv4 address
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - name: "OpenBao - Is running"
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200/v1/sys/mounts"
        headers:
          X-Vault-Token: "{{ hostvars[inventory_hostname]['openbao_token'] }}"
          status_code: "200"
    - name: "OpenBao - Setup key value storage v2"
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200/v1/sys/mounts/{{ hostvars[inventory_hostname]['openbao_secrets_path'] }}"
        method: POST
        headers:
          X-Vault-Token: "{{ hostvars[inventory_hostname]['openbao_token'] }}"
        body: "{\"type\":\"kv-v2\"}"
        body_format: json
        status_code: [200,400]
      register: response
    - name: "OpenBao - Key Value Storage - Fail if not 200 or 400 with error 'path is already in use'"
      fail:
        msg: "Request failed with status code {{ response.status }} and message: {{ response.msg }}"
      when:
        - response.status != 200
        - not (response.status == 400 and response.json.errors is search("path is already in use"))
    - name: "OpenBao - Cipher key"
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200/v1/{{ hostvars[inventory_hostname]['openbao_secrets_path'] }}/data/{{ hostvars[inventory_hostname]['openbao_secrets_creds'] }}"
        method: PUT
        body: "{ \"options\": {\"cas\": 0}, \"data\": {\"cipherKey\": \"{{ hostvars[inventory_hostname]['openbao_cipher_key'] }}\"} }"
        body_format: json
        status_code: [200,400]
        headers:
          X-Vault-Token: "{{ hostvars[inventory_hostname]['openbao_token'] }}"
      register: response
    - name: "OpenBao - Cipher Key - Fail if not 200 or 400 with error 'check-and-set parameter did not match the current version'"
      fail:
        msg: "Request failed with status code {{ response.status }} and message: {{ response.msg }}"
      when:
        - response.status != 200
        - not (response.status == 400 and response.json.errors is search("check-and-set parameter did not match the current version"))
